version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:5001
    depends_on:
      - backend
    networks:
      - vigovia-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5001"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./backend/generated-pdfs:/app/generated-pdfs
      - ./backend/temp:/app/temp
    networks:
      - vigovia-network
    restart: unless-stopped

networks:
  vigovia-network:
    driver: bridge

volumes:
  pdf-storage:
  temp-storage:
